"""Audio backend contract."""

from pathlib import Path
from typing import Protocol, runtime_checkable

from party_player.equalizer import ResolvedEqualizerPreset


@runtime_checkable
class RuntimeClipProtectionBackend(Protocol):
    """Optional backend capability for a real-time output limiter."""

    def supports_runtime_clip_protection(self) -> bool: ...

    def set_runtime_clip_protection(
        self,
        enabled: bool,
        ceiling_dbfs: float,
    ) -> bool:
        """Apply limiter state and return whether the backend accepted it."""
        ...


@runtime_checkable
class EqualizerBackend(Protocol):
    """Optional backend capability for independent per-player equalizers."""

    def equalizer_band_frequencies(self) -> tuple[float, ...]: ...
    def apply_equalizer(self, preset: ResolvedEqualizerPreset) -> bool: ...


class AudioBackend(Protocol):
    def maximum_volume_factor(self) -> float: ...
    def list_output_devices(self) -> list[tuple[str, str]]: ...
    def set_output_device(self, device_id: str) -> None: ...
    def prepare(self, file_path: Path) -> object: ...
    def load_prepared(self, file_path: Path, prepared: object) -> None: ...
    def release_prepared(self, prepared: object) -> None: ...
    def load(self, file_path: Path) -> None: ...
    def play(self) -> None: ...
    def pause(self) -> None: ...
    def resume(self) -> None: ...
    def stop(self) -> None: ...
    def seek(self, position_seconds: float) -> None: ...
    def set_volume(self, volume: float) -> None: ...
    def get_position(self) -> float: ...
    def get_duration(self) -> float: ...
    def is_playing(self) -> bool: ...
    def is_paused(self) -> bool: ...
    def is_finished(self) -> bool: ...
    def playback_state(self) -> str: ...
    def close(self) -> None: ...
